"""Shared protocol types for Omni Vox 2."""

from omnivox_protocol.audio import (
    AUDIO_HEADER_BYTES,
    MAX_BINARY_FRAME_BYTES,
    AudioCodec,
    AudioFrame,
    decode_audio_frame,
    encode_audio_frame,
)
from omnivox_protocol.control import (
    MAX_CONTROL_FRAME_BYTES,
    PROTOCOL_VERSION,
    Hello,
    decode_hello,
    encode_hello,
)
from omnivox_protocol.errors import ProtocolViolation
from omnivox_protocol.heartbeat import (
    Heartbeat,
    Ping,
    Pong,
    decode_heartbeat,
    encode_heartbeat,
)
from omnivox_protocol.interaction import (
    CancelReason,
    CancelRequest,
    ClientMessage,
    UtteranceEnd,
    UtteranceStart,
    Wake,
    WireRequest,
    decode_client_message,
    encode_client_message,
)
from omnivox_protocol.models import (
    AudioChunk,
    AudioInput,
    Cancelled,
    Completed,
    PipelineEvent,
    RequestContext,
    ResponseText,
    SpokenAudio,
    TextSegment,
    Transcript,
    TranscriptReady,
)
from omnivox_protocol.welcome import (
    ProtocolLimits,
    Welcome,
    decode_welcome,
    encode_welcome,
)
from omnivox_protocol.wire_error import (
    ErrorCode,
    ErrorMessage,
    decode_error_message,
    encode_error_message,
)

__all__ = [
    "AUDIO_HEADER_BYTES",
    "MAX_BINARY_FRAME_BYTES",
    "MAX_CONTROL_FRAME_BYTES",
    "PROTOCOL_VERSION",
    "AudioChunk",
    "AudioCodec",
    "AudioFrame",
    "AudioInput",
    "CancelReason",
    "CancelRequest",
    "Cancelled",
    "ClientMessage",
    "Completed",
    "ErrorCode",
    "ErrorMessage",
    "Heartbeat",
    "Hello",
    "Ping",
    "PipelineEvent",
    "Pong",
    "ProtocolLimits",
    "ProtocolViolation",
    "RequestContext",
    "ResponseText",
    "SpokenAudio",
    "TextSegment",
    "Transcript",
    "TranscriptReady",
    "UtteranceEnd",
    "UtteranceStart",
    "Wake",
    "Welcome",
    "WireRequest",
    "decode_audio_frame",
    "decode_client_message",
    "decode_error_message",
    "decode_heartbeat",
    "decode_hello",
    "decode_welcome",
    "encode_audio_frame",
    "encode_client_message",
    "encode_error_message",
    "encode_heartbeat",
    "encode_hello",
    "encode_welcome",
]
